// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

type Product struct {
	ID    int64   `json:"id"`
	Name  string  `json:"name"`
	Img   string  `json:"img"`
	Price float64 `json:"price"`
}
