// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

type Allergen struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Img  string `json:"img"`
	Info string `json:"info"`
}

type Product struct {
	ID    int64   `json:"id"`
	Name  string  `json:"name"`
	Img   string  `json:"img"`
	Price float64 `json:"price"`
}

type ProductAllergen struct {
	ID         int64 `json:"id"`
	ProductFk  int64 `json:"product_fk"`
	AllergenFk int64 `json:"allergen_fk"`
}

type User struct {
	Uuid    string `json:"uuid"`
	Name    string `json:"name"`
	Email   string `json:"email"`
	Address string `json:"address"`
	Role    string `json:"role"`
}
